name: Deploy

on:
  push:
    branches: [ master ]
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        node-version: [18.x]
          
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: deployment
        run: |
          touch ./environments/.prod.env
          echo REACT_APP_BACKEND_URL=https://api.finuncle.com/ > ./environments/.prod.env
          echo REACT_APP_BACKEND_API=https://api.finuncle.com/api/ > ./environments/.prod.env
          echo REACT_APP_API_BASE_URL="https://api.finuncle.com/api" > ./environments/.prod.env
          echo REACT_APP_V1_API_URL="https://api.finuncle.com/api/v1" > ./environments/.prod.env
          echo REACT_APP_TOKEN_BASE_URL="https://api.finuncle.com/token" > ./environments/.prod.env
          echo REACT_APP_USER_BASE_URL="https://api.finuncle.com/users/api/users" > ./environments/.prod.env
          npm run build:prod
